name: aerospike-tools-validate

dependency:
  - url: git@github.com:aerospike/aerospike-client-c
    dir: client
    ref: 6.6.1

container:
  - base:
      - docker.qe.aerospike.com/build/aerospike-tools-alt:rhel-8
      - docker.qe.aerospike.com/build/aerospike-tools-alt:rhel-9
      - docker.qe.aerospike.com/build/aerospike-tools-alt:amazonlinux-2023
      - docker.qe.aerospike.com/build/aerospike-tools-alt:debian-10
      - docker.qe.aerospike.com/build/aerospike-tools-alt:debian-11
      - docker.qe.aerospike.com/build/aerospike-tools-alt:debian-12
      - docker.qe.aerospike.com/build/aerospike-tools-alt:ubuntu-18.04
      - docker.qe.aerospike.com/build/aerospike-tools-alt:ubuntu-20.04
      - docker.qe.aerospike.com/build/aerospike-tools-alt:ubuntu-22.04
      - docker.qe.aerospike.com/build/aerospike-tools-alt:ubuntu-24.04

      - docker.qe.aerospike.com/build/aerospike-tools-alt:arm-rhel-8
      - docker.qe.aerospike.com/build/aerospike-tools-alt:arm-rhel-9
      - docker.qe.aerospike.com/build/aerospike-tools-alt:arm-amazonlinux-2023
      - docker.qe.aerospike.com/build/aerospike-tools-alt:arm-debian-11
      - docker.qe.aerospike.com/build/aerospike-tools-alt:arm-debian-12
      # - docker.qe.aerospike.com/build/aerospike-tools-alt:arm-ubuntu-18.04
      - docker.qe.aerospike.com/build/aerospike-tools-alt:arm-ubuntu-20.04
      - docker.qe.aerospike.com/build/aerospike-tools-alt:arm-ubuntu-22.04
      - docker.qe.aerospike.com/build/aerospike-tools-alt:arm-ubuntu-24.04

build:
  - name: default
    environment:
      CLIENTREPO: /work/source/client
    script:
      - make -C client
      - make
      - make $PKG
    artifact:
      - bin/*
      - target/packages/*
