name: aerospike-tools-validate

dependency:
  - url: git@github.com:aerospike/aerospike-client-c
    dir: client
    ref: 6.6.5

container:
  - base:
      - docker.qe.aerospike.com/build/aerospike-tools:rhel-8
      - docker.qe.aerospike.com/build/aerospike-tools:rhel-9
      - docker.qe.aerospike.com/build/aerospike-tools:amazonlinux-2023
      - docker.qe.aerospike.com/build/aerospike-tools:debian-10
      - docker.qe.aerospike.com/build/aerospike-tools:debian-11
      - docker.qe.aerospike.com/build/aerospike-tools:debian-12
      - docker.qe.aerospike.com/build/aerospike-client-c:debian-13
      - docker.qe.aerospike.com/build/aerospike-tools:ubuntu-18.04
      - docker.qe.aerospike.com/build/aerospike-tools:ubuntu-20.04
      - docker.qe.aerospike.com/build/aerospike-tools:ubuntu-22.04
      - docker.qe.aerospike.com/build/aerospike-tools:ubuntu-24.04

      - docker.qe.aerospike.com/build/aerospike-tools:arm-rhel-8
      - docker.qe.aerospike.com/build/aerospike-tools:arm-rhel-9
      - docker.qe.aerospike.com/build/aerospike-tools:arm-amazonlinux-2023
      - docker.qe.aerospike.com/build/aerospike-tools:arm-debian-11
      - docker.qe.aerospike.com/build/aerospike-tools:arm-debian-12
      - docker.qe.aerospike.com/build/aerospike-client-c:arm-debian-13
      - docker.qe.aerospike.com/build/aerospike-tools:arm-ubuntu-20.04
      - docker.qe.aerospike.com/build/aerospike-tools:arm-ubuntu-22.04
      - docker.qe.aerospike.com/build/aerospike-tools:arm-ubuntu-24.04

build:
  - name: default
    environment:
      CLIENTREPO: /work/source/client
    script:
      - make -C client
      - make
      - make $PKG
    artifact:
      - bin/*
      - target/packages/*
