name: aerospike-tools-validate

dependency:
  - url: git@github.com:aerospike/aerospike-client-c
    dir: client
    ref: 6.6.0

container:
  - base:

      - docker.qe.aerospike.com/build/aerospike-tools:centos-7
      - docker.qe.aerospike.com/build/aerospike-tools:centos-8
      - docker.qe.aerospike.com/build/aerospike-tools:debian-8
      - docker.qe.aerospike.com/build/aerospike-tools:debian-9
      - docker.qe.aerospike.com/build/aerospike-tools:debian-10
      - docker.qe.aerospike.com/build/aerospike-tools:ubuntu-18.04
      - docker.qe.aerospike.com/build/aerospike-tools:ubuntu-20.04

build:
  - name: default
    environment:
      CLIENTREPO: /work/source/client
    script:
      - make -C client
      - make
      - make $PKG
    artifact:
      - bin/*
      - target/packages/*
