# Build asvalidation rpm distribution.

export RPM_SOURCE_ROOT = $(shell echo `pwd`/dist)
export RPM_BUILD_ROOT = $(RPM_SOURCE_ROOT)/BUILD
export CL_BASE = $(RPM_BUILD_ROOT)/opt/aerospike
export ETC_BASE = $(RPM_BUILD_ROOT)/etc/aerospike

MANIFEST_DIR = manifest/TEMP
# Package version from git tags (build/version is the single source of truth):
# master -> x.y.z; dev branches -> x.y.z-<n>-g<sha>. rpm forbids '-' in Version, so
# map the dev describe suffix's hyphens to underscores.
REV = $(shell build/version -v)
RPM_VERSION = $(subst -,_,$(REV))
# Build number from build/version -r (1-based: tagged release and dev builds are 1);
# becomes the rpm Release so successive master builds are orderable.
BUILD_NUMBER = $(shell build/version -r)
RPM_RELEASE = $(BUILD_NUMBER)
OS = $(shell build/os_version)
ARCH = $(shell uname -m)

.PHONY: default
default: dist
	mkdir -p target/packages
	mkdir -p $(RPM_BUILD_ROOT)
	mkdir -p $(RPM_SOURCE_ROOT)/RPMS/$(ARCH)
	mkdir -p $(RPM_BUILD_ROOT)/usr/bin

	sed 's/@VERSION@/'$(RPM_VERSION)'/g' <pkg/rpm/asvalidation.spec >pkg/asvalidation_v.spec
	sed -i 's/@RELEASE@/'$(RPM_RELEASE)'/g' pkg/asvalidation_v.spec
	sed -i 's/@ARCH@/'$(ARCH)'/g' pkg/asvalidation_v.spec

	rpmbuild --noclean -bb -vv --define "dist .$(OS)" --buildroot $(RPM_BUILD_ROOT) pkg/asvalidation_v.spec
	find $(RPM_SOURCE_ROOT)/RPMS -type f -exec mv {} target/packages \;
	rm -rf pkg/asvalidation_v.spec dist

distclean:
	rm -rf $(RPM_BUILD_ROOT)
	rm -rf target/packages/*.rpm

.PHONY: dist
dist:

	mkdir -p $(CL_BASE)
	mkdir -p $(CL_BASE)/bin

	# asvalidation
	install -m 755 bin/asvalidation $(CL_BASE)/bin/asvalidation

print-% : ; @echo $($*)
