# Build asvalidation distribution.

export DEB_SOURCE_ROOT = $(shell echo `pwd`/dist)
export DEB_BUILD_ROOT = $(DEB_SOURCE_ROOT)/BUILD
export CL_BASE = $(DEB_BUILD_ROOT)/opt/aerospike
export ETC_BASE = $(DEB_BUILD_ROOT)/etc/aerospike

# Package version from git tags (build/version is the single source of truth):
# master -> x.y.z; dev branches -> x.y.z-<n>-g<sha> (full git describe).
REV = $(shell build/version -v)
# Build number from build/version -r (1-based: tagged release and dev builds are 1).
# It goes in the debian revision (with the OS); no +1 in this Makefile.
BUILD_NUMBER = $(shell build/version -r)
DEB_REVISION = $(BUILD_NUMBER)$(OS)
OS = $(shell build/os_version)
ARCH=$(shell uname -m)
MANIFEST_DIR = manifest/TEMP

ifeq ($(ARCH), x86_64)
	ARCH=amd64
endif

ifeq ($(ARCH), aarch64)
        ARCH=arm64
endif

.PHONY: default
default: dist

.PHONY: dist
dist:

	# Build asvalidation package.
	rm -rf $(DEB_BUILD_ROOT)/*
	mkdir -p $(DEB_BUILD_ROOT)/DEBIAN
	mkdir -p $(DEB_BUILD_ROOT)/usr/bin
	mkdir -p target/packages
	install -m 755 pkg/deb/postinst $(DEB_BUILD_ROOT)/DEBIAN/postinst
	install -m 755 pkg/deb/prerm $(DEB_BUILD_ROOT)/DEBIAN/prerm
	install -m 644 pkg/deb/control $(DEB_BUILD_ROOT)/DEBIAN/control

	mkdir -p $(CL_BASE)
	mkdir -p $(CL_BASE)/bin

        # asvalidation
	install -m 755 bin/asvalidation $(CL_BASE)/bin/asvalidation

	# Create symlinks to /usr/bin
	mkdir -p $(DEB_BUILD_ROOT)/usr/bin
	ln -sf /opt/aerospike/bin/asvalidation $(DEB_BUILD_ROOT)/usr/bin/asvalidation


	sed 's/@VERSION@/'$(REV)-$(DEB_REVISION)'/g' <pkg/deb/control >$(DEB_BUILD_ROOT)/DEBIAN/control
	sed -i 's/@ARCH@/'$(ARCH)'/g' $(DEB_BUILD_ROOT)/DEBIAN/control

	fakeroot dpkg-deb -Z xz --build $(DEB_BUILD_ROOT) target/packages/asvalidation_$(REV)-$(DEB_REVISION)_$(ARCH).deb
	rm -rf dist

distclean:
	rm -rf $(DEB_SOURCE_ROOT)
	rm -rf pkg/deb/DEBS

print-% : ; @echo $($*)
